@host = http://localhost
# debug: 4040
# dev: 3003
@port = 3003 
@APIAddress = {{host}}:{{port}}
@id = 687562d583664579fc4124ff
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlciIsImlkIjoiNjg3NTcyOTUyZTRmNDMzODQ5MTg5NTU4IiwiaWF0IjoxNzUyNTI3NTEyfQ.pgwF7nbm386k-p2E-fpJ9PvJPFk7rx2b9uOu-LHwvwk

GET {{APIAddress}}/api/blogs
Accept: application/json
###

POST {{APIAddress}}/api/blogs
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 5
}

###
PUT {{APIAddress}}/api/blogs/{{id}}
Accept: application/json
Content-Type: application/json


{
    "title": "Changed blog",
    "url": "changed.com"
}

###
DELETE {{APIAddress}}/api/blogs/{{id}}
Accept: application/json
Authorization: Bearer {{token}}

###