@host = http://localhost
# debug: 4040
# dev: 3003
@port = 3003 
@APIAddress = {{host}}:{{port}}
@id = 687562d583664579fc4124ff
@token = {{$processEnv TOKEN}}

GET {{APIAddress}}/api/blogs
Accept: application/json
###

POST {{APIAddress}}/api/blogs
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7
}

###
PUT {{APIAddress}}/api/blogs/{{id}}
Accept: application/json
Content-Type: application/json


{
    "title": "Changed blog",
    "url": "changed.com"
}

###
DELETE {{APIAddress}}/api/blogs/{{id}}
Accept: application/json
Authorization: Bearer {{token}}

###