@host = http://localhost
# debug: 4040
# dev: 3003
@port = 3003 
@APIAddress = {{host}}:{{port}}
@id = 681ec82f8d9cfd4aaf787379


POST {{APIAddress}}/api/login
Accept: application/json
Content-Type: application/json


{
    "username": "normaluser",
    "password": "normalcontraseña"
}

###